const translations = {
    en: {
        "about-href": "About",
        "play-href": "Play",
        "news-href": "News",
        "youhave": "You have only",
        "oneshot_text": "OneShot",
        "register": "Sign Up",
        "signinbutton": "Sign In",
        "registerbutton": "Sign Up",
        "signintext": "Sign In",
        "registertext": "Sign Up",
        "emailtext": "Email",
        "passwordtext": "Password",
        "signintextogo": "Sign In",
        "registertextogo": "Sign Up",
        "passwordagaintext": "Confirm Password",
        "resources-href": "Resources",
        "resources-one": "OST",
        "resources-two": "Wiki",
        "resources-three": "Community",
        "play-one": "Play OneShot",
        "play-two": "Steam Page",
        "warning": "To run OneShot, you must have the Steam client installed.",
        "warning_two": "Continue?",
        "confirm": "Yes",
        "cancel": "No",
        "about_0": "About developers",
        "about_1": "OneShot is created by independent studio Future Cat, founded by three developers: Nightmargin (Casey Gu), Eliza Velasquez, and Michael Shirt.",
        "about_2": "Developers:",
        "about_3": "Nightmargin (Casey Gu) - Game Design, Programming, Art",
        "about_4": "Eliza Velasquez - Art, Animation",
        "about_5": "Michael Shirt - Programming, Sound Design",
        "about_6": "About OneShot",
        "about_7": "OneShot is a puzzle-adventure game known for its unique meta-narrative structure. The player interacts with the protagonist, Niko, to help him bring light back to a dark world. The game uses elements that go beyond traditional gameplay, involving the player in interacting with the game's files and operating system.",
        "about_8": "In OneShot, players guide Niko, a child who awakens in a mysterious world devoid of sunlight. Tasked with restoring the sun in the tower, Niko embarks on a journey that involves solving puzzles and interacting with the environment. The game is notable for its metafictional elements, where the world appears to acknowledge the player's existence, creating a unique and immersive",
        "about_9": "Development Timeline",
        "about_10": "2014: OneShot was first released on the RPG Maker forums.",
        "about_11": "2016: The game was officially released on Steam, gaining popularity and critical acclaim.",
        "about_12": "2024: The World Machine Edition was released.",
        "about_13": "Gameplay Mechanics",
        "about_14": "OneShot features traditional adventure game mechanics, such as puzzle-solving and item combination. However, it distinguishes itself with its metafictional elements. For instance, the game may prompt the player to interact with the computer's operating system outside the game window, creating a sense of immersion and blurring the lines between the game world and reality.",
        "about_15": "Art and Sound Design",
        "about_16": "The game's art style is characterized by pixel art with a minimalist design, contributing to its surreal atmosphere. The soundtrack, composed by Velasquez, Nightmargin, and Michael Shirt, complements the game's tone and enhances the emotional impact of the narrative.",
        "about_17": "Reviews",
        "about_18": "OneShot received positive reviews for its innovative gameplay, emotional storytelling, and unique art style. Critics praised its ability to engage players on a personal level, making them feel like an integral part of the story. The game's metafictional elements were particularly well-received, as they added depth to the narrative and created a memorable experience.",
    },
    uk: {
        "about-href": "Про гру",
        "play-href": "Грати",
        "news-href": "Новини",
        "youhave": "У вас є лише",
        "oneshot_text": "ОднаСпроба",
        "register": "Реєстрація",
        "signinbutton": "Увійти",
        "registerbutton": "Зареєструватися",
        "signintext": "Увійти",
        "registertext": "Зареєструватися",
        "emailtext": "Електронна пошта",
        "passwordtext": "Пароль",
        "signintextogo": "Увійти",
        "registertextogo": "Зареєструватися",
        "passwordagaintext": "Підтвердіть пароль",
        "resources-href": "Ресурси",
        "resources-one": "Саундтрек",
        "resources-two": "Вікіпедія",
        "resources-three": "Спільнота",
        "play-one": "Грати у OneShot",
        "play-two": "Сторінка Steam",
        "warning": "Для запуска OneShot, необхідно мати встановлений клієнт Steam.",
        "warning_two": "Продовжити?",
        "confirm": "Так",
        "cancel": "Ні",
        "about_0": "Про розробників",
        "about_1": "OneShot створена незалежною студією Future Cat, заснованою трьома розробниками: Nightmargin (Кейсі Гу), Елізою Веласкес і Майклом Шертом. Вони працюють над грою в США та Канаді.",
        "about_2": "Розробники:",
        "about_3": "Nightmargin (Кейсі Гу) - Дизайн гри, програмування, малювання",
        "about_4": "Еліза Веласкес - Малювання, анімація",
        "about_5": "Майкл Шерт - Програмування, звуковий дизайн",
        "about_6": "Про гру OneShot",
        "about_7": "OneShot - це головоломка-пригодницька гра, відома своєю унікальною мета-оповідною структурою. Гравець взаємодіє з протагоністом Ніко, щоб допомогти йому повернути світло в темний світ. Гра використовує елементи, які виходять за межі традиційного ігрового процесу, залучаючи гравця до взаємодії з файлами гри та операційною системою.",
        "about_8": "Ніко є дитиною, що прокидається в таємничому світі без сонця. Завданням є відновлення сонця в башті, Ніко вирушає в подорож, що включає розв'язання головоломок і взаємодію з навколишнім середовищем. Гра відзначається метафікційними елементами, де світ, здається, визнає існування гравця, створюючи унікальну та захоплюючу",
        "about_9": "Хронологія розробки",
        "about_10": "2014: OneShot вперше була випущена на форумах RPG Maker.",
        "about_11": "2016: Гра була офіційно випущена на Steam, здобувши популярність і критичне визнання.",
        "about_12": "2024: Випущено World Machine Edition.",
        "about_13": "Механіки гри",
        "about_14": "OneShot має традиційну механіку пригодницьких ігор, таку як розв'язання головоломок і комбінація предметів. Однак вона відрізняється метафікційними елементами. Наприклад, гра може запропонувати гравцеві взаємодіяти з операційною системою комп'ютера поза вікном гри, створюючи відчуття занурення та розмиваючи межі між ігровим світом і реальністю.",
        "about_15": "Малювання та звуковий дизайн",
        "about_16": "Стиль малювання гри характеризується піксельним мистецтвом з мінімалістичним дизайном, що сприяє її сюрреалістичній атмосфері. Саундтрек, написаний Веласкесом, Найтмаргіном і Майклом Шертом, доповнює тон гри та підсилює емоційний вплив наративу.",
        "about_17": "Відгуки",
        "about_18": "OneShot отримала позитивні відгуки за інноваційний ігровий процес, емоційне оповідання та унікальний стиль малювання. Критики похвалили її здатність залучати гравців на особистому рівні, змушуючи їх відчувати себе невід'ємною частиною історії. Метафікційні елементи гри були особливо добре сприйняті, оскільки вони додали глибині наративу та створили незабутній досвід.",
    }
};